export const ADD_COURSE = 'ADD_COURSE';
export const REMOVE_COURSE = 'REMOVE_COURSE';
export const COURSE_SELECTED = 'COURSE_SELECTED';

export const ADD_CATEGORY_TO_COURSE = 'ADD_CATEGORY_TO_COURSE';
export const REMOVE_CATEGORY_FROM_COURSE = 'REMOVE_CATEGORY_FROM_COURSE';
export const EDIT_CATEGORY_IN_COURSE = 'EDIT_CATEGORY_IN_COURSE';

export const ADD_ASSIGNMENT_TO_CATEGORY = 'ADD_ASSIGNMENT_TO_CATEGORY';
export const REMOVE_ASSIGNMENT_FROM_CATEGORY = 'REMOVE_ASSIGNMENT_FROM_CATEGORY';
export const EDIT_ASSIGNMENT_IN_CATEGORY = 'EDIT_ASSIGNMENT_IN_CATEGORY';

export const AUTH_START = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_DRAWER = 'SET_DRAWER';

export const FETCH_USER_DATA_FAIL = 'FETCH_USER_DATA_FAIL';
export const FETCH_USER_DATA_START = 'FETCH_USER_DATA_START';
export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS';

export const SAVE_USER_DATA_FAIL = 'SAVE_USER_DATA_FAIL';
export const SAVE_USER_DATA_START = 'SAVE_USER_DATA_START';
export const SAVE_USER_DATA_SUCCESS = 'SAVE_USER_DATA_SUCCESS';