// UI 
export const SET_DRAWER_STATE = 'SET_DRAWER_STATE'

// AUTH
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

// DATA
export const FETCH_USER_DATA = 'FETCH_USER_DATA'