// UI 
export const SET_DRAWER_STATE = 'SET_DRAWER_STATE'
export const COURSE_SELECTED = 'COURSE_SELECTED'
export const SET_ADD_COURSE_DIALOG_STATE = 'SET_ADD_COURSE_DIALOG_STATE'
export const SET_SELECTED_CATEGORY_NAME = 'SET_SELECTED_CATEGORY_NAME'
export const SET_ADD_ASSIGNMENT_DIALOG_STATE = 'SET_ADD_ASSIGNMENT_DIALOG_STATE'

// AUTH
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

// DATA
export const FETCH_USER_DATA = 'FETCH_USER_DATA'
export const ADD_CATEGORY_TO_COURSE = 'ADD_CATEGORY_TO_COURSE'
export const REMOVE_CATEGORY_FROM_COURSE = 'REMOVE_CATEGORY_FROM_COURSE'
export const EDIT_CATEGORY_IN_COURSE = 'EDIT_CATEGORY_IN_COURSE'